image: "rust:latest"
test:cargo:
  script:
    - rustup default
    - rustc --version && cargo --version  # Print version info for debugging
    - rustup component list
    - rustup component add clippy
    - cargo test --workspace --verbose
    - cargo build --release
    - cargo clippy --message-format=json -- -W clippy::pedantic | ./target/release/lint-lab lints -i - -o gl-code-quality-report.json
    - cargo run -- stats --format open-metrics -o metrics.txt
    - cargo +nightly fmt --message-format=json | ./target/release/lint-lab fmt -i -
  artifacts:
    reports:
      metrics: metrics.txt
      codequality: gl-code-quality-report.json
