image: "rust:latest"
test:cargo:
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo test --workspace --verbose
    - cargo clippy --message-format=json -- -D clippy::pedantic | cargo run -- lints -i - -o gl-code-quality-report.json
    - cargo run -- stats --format open-metrics -o gl-code-quality-report.json
  artifacts:
    reports:
      metrics: metrics.txt
      codequality: gl-code-quality-report.json
